import { expect, it } from "vitest";

import { studioClientModule, studioStyles, type StudioClientImports } from "./studio-ui.js";

const client = studioClientModule({} as StudioClientImports);
const styles = studioStyles();

it("wires the constrained Rich Text and Monaco editors", () => {
  expect(client).toContain("MDXEditor");
  expect(client).toContain("lucide-react");
  expect(client).toContain("Rich Text");
  expect(client).toContain("format_align_left: AlignLeft");
  expect(client).toContain("format_align_center: AlignCenter");
  expect(client).toContain("format_align_right: AlignRight");
  expect(client).not.toContain('aria-label="Markdown formatting"');
  expect(client).toContain('import { Button, Select, Tooltip, TooltipProvider } from "@cloudflare/kumo"');
  expect(client).toContain('import "@cloudflare/kumo/styles/standalone"');
  expect(client).toContain('import * as monaco from "monaco-editor"');
  expect(client).toContain('import EditorWorker from "monaco-editor/editor/editor.worker.js?worker"');
  expect(client).toContain('import "monaco-editor/languages/definitions/markdown/register.js"');
  expect(client).toContain("function frontmatterEditorDecorations(model)");
  expect(client).toContain("editor.createDecorationsCollection(frontmatterEditorDecorations(model))");
  expect(client).toContain("frontmatterDecorations.set(frontmatterEditorDecorations(model))");
  expect(client).toContain("monaco.editor.createModel");
  expect(client).toContain('monaco.editor.createModel(value, "markdown"');
  expect(client).toContain("model.pushEditOperations");
  expect(client).toContain("fontSize: 14");
  expect(client).toContain("lineHeight: 24");
  expect(client).toContain("lineDecorationsWidth: 22");
  expect(client).toContain("glyphMargin: true");
  expect(client).toContain('cursorBlinking: "smooth"');
  expect(client).toContain('cursorSmoothCaretAnimation: "on"');
  expect(client).toContain('renderLineHighlightOnlyWhenFocus: true');
  expect(client).toContain("unicodeHighlight: {");
  expect(client).toContain("nonBasicASCII: false");
  expect(client).toContain("ambiguousCharacters: false");
  expect(client).toContain("invisibleCharacters: true");
  expect(client).toContain("onSustainedEdit");
  expect(client).toContain("}, 520)");
  expect(client).toContain('type: "scribe:reveal-source"');
  expect(client).toContain('className="source-monaco"');
  expect(client).not.toContain("source-line-number");
  expect(client).not.toContain("source-highlight");
  expect(client).not.toContain("highlightMarkdownLine");
});

it("preserves recovery, lease, and mutation failure behavior", () => {
  expect(client).toContain('new EventSource("/__scribe/api/events")');
  expect(client).toContain("scheduleOpenDocument");
  expect(client).toContain("scribe-studio-recovery");
  expect(client).toContain("Math.max(studioRevision, body.revision)");
  expect(client).toContain("next.revision < studioRevision");
  expect(client).toContain("Your browser recovery draft remains intact");
  expect(client).toContain("transaction.onabort = () => reject(transaction.error)");
  expect(client).toContain("const [writer, setWriter] = useState(null)");
  expect(client).toContain("writer === false");
  expect(client).toContain("const putDraft = useCallback");
  expect(client).toContain('if (!response.ok || typeof body.source !== "string")');
  expect(client).toContain("const flushed = await flushMarkdown()");
  expect(client).toContain("if (!flushed)");
  expect(client).toContain("baseDiskVersion: body.diskVersion");
  expect(client).not.toContain("revision: revisionRef.current");
});

it("renders only the restrained Studio shell and operational status", () => {
  expect(client).not.toContain("<strong>Scribe Studio</strong>");
  expect(client).not.toContain("production renderer");
  expect(client).not.toContain("detected</span>");
  expect(client).not.toContain('title="Markdown"');
  expect(client).not.toContain('title="Preview"');
  expect(client).toContain("<Select");
  expect(client).toContain("<Select.Option");
  expect(client).toContain('{ value: "fit", label: "Fit pane" }');
  expect(client).toContain('const [viewport, setViewport] = useState("fit")');
  expect(client).toContain("fitSelectedViewport");
  expect(client).toContain("new ResizeObserver(fitSelectedViewport)");
  expect(client).not.toContain('<select aria-label="Preview viewport"');
  expect(client).toContain('role="separator"');
  expect(client).toContain('aria-orientation="vertical"');
  expect(client).toContain("function splitBoundsForWidth(width)");
  expect(client).toContain("aria-valuemin={Math.round(minimumSplit)}");
  expect(client).toContain("onDoubleClick={() => setSplit(50)}");
  expect(client).toContain("dragOffset.current");
  expect(client).not.toContain("updateSplit(event.clientX);");
  expect(client).toContain('iframeRef.current?.contentWindow?.postMessage({ type: "scribe:theme", theme }, location.origin)');
  expect(client).not.toContain('const src = "/preview?theme=" + theme');
  expect(client).toContain('className="studio-statusbar"');
  expect(client).toContain("{location.host}");
  expect(client).toContain('data-save-state={saveStatus}');
  expect(client).toContain('"Resolve conflict"');
  expect(client).toContain('data-status={connectionStatus}');
  expect(client).toContain('aria-controls={saveStatus === "conflict" ? "studio-conflict-card" : undefined}');
  expect(client).not.toContain('className="save-control" data-state={saveStatus}');
  expect(client).toContain('className="studio-toaster"');
  expect(client).toContain('"editor.background": "#111113"');
  expect(client).toContain('"editorGutter.background": "#111113"');
});

it("styles the workspace, Monaco editor, preview, and toaster consistently", () => {
  expect(styles).toContain("#2563eb");
  expect(styles).toContain("--studio-canvas: #0d0d0f");
  expect(styles).toContain("--studio-panel: #111113");
  expect(styles).toContain("--studio-shell: #161618");
  expect(styles).toContain("--studio-control: #1c1c1f");
  expect(styles).toContain("--studio-border: #29292d");
  expect(styles).toContain("--studio-text: #f2f2f3");
  expect(styles).toContain("--studio-muted: #8e8e96");
  expect(styles).toContain("grid-template-rows:2.875rem minmax(0,1fr) 1.75rem");
  expect(styles).not.toContain("#CDFF57");
  expect(styles).not.toContain("#BFFF36");
  expect(styles).not.toContain("linear-gradient");
  expect(styles).toContain("grid-template-columns:minmax(20rem,var(--studio-split)) 1px minmax(20rem,1fr)");
  expect(styles).toContain("transition:grid-template-columns 320ms cubic-bezier(.22,1,.36,1)");
  expect(styles).toContain(".is-resizing-studio .studio-workspace { transition:none; }");
  expect(styles).toMatch(/\.viewport-select\s*\{[^}]*min-inline-size:7\.25rem[^}]*background:var\(--studio-control\)!important;/u);
  expect(styles).toContain(".source-monaco .monaco-editor");
  expect(styles).toMatch(/\.source-monaco \.monaco-editor \.margin\s*\{[^}]*background:var\(--studio-panel\)!important;/u);
  expect(styles).not.toContain("box-shadow:inset -1px 0 0 #2a2a2e");
  expect(styles).toContain(".source-monaco .line-numbers { font-variant-numeric:tabular-nums; text-align:center!important;");
  expect(styles).toContain(".source-monaco .line-numbers.active-line-number { color:var(--studio-accent)!important;");
  expect(styles).toContain(".source-monaco .source-frontmatter-key { color:#60a5fa!important;");
  expect(styles).toContain(".source-monaco .source-frontmatter-delimiter { color:#2563eb!important;");
  expect(styles).toMatch(/\.preview-stage\s*\{[^}]*display:grid;[^}]*place-items:stretch center;[^}]*overflow:hidden;[^}]*padding:0/u);
  expect(styles).toContain("white-space:pre-wrap");
  expect(styles).toContain("overflow-wrap:anywhere");
  expect(styles).toContain("transition:inline-size 320ms cubic-bezier(.22,1,.36,1)");
  expect(styles).toMatch(/\.preview-device\s*\{[^}]*inline-size:min\(100%,var\(--preview-width\)\);[^}]*border:0;[^}]*border-radius:0/u);
  expect(styles).toContain(".connection-status[data-status=readonly]");
  expect(styles).toContain("font:.6875rem/1 var(--studio-mono)");
  expect(styles).toContain(".studio-toaster");
});
